/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) {
        Caneta c = new Caneta();
        c.setCor("azul");
        c.setNivelTinta(80);
        System.out.println(c.desenhar(10));
        System.out.println(c.desenhar(-10));
        System.out.println(c.getCor());
        System.out.println(c.getNivelTinta());

        Caneta d = new Caneta();
        d.setCor("roxa");
        d.setNivelTinta(63);
        System.out.println(d.desenhar(73));
        System.out.println(d.getCor());
        System.out.println(d.getNivelTinta());

        Contador contador = new Contador();
        contador.setValor(12);
        contador.incrementar();
        contador.incrementar();
        contador.incrementar();
        contador.incrementar();
        contador.incrementar();
        contador.incrementar();
        System.out.println(contador.getValorAtual());

        BuzzLightyear b = new BuzzLightyear();
        System.out.println(b.dizFrase());
        System.out.println(b.capaceteRetratil());
        System.out.println(b.capaceteRetratil());
        System.out.println(b.capaceteRetratil());
        System.out.println(b.capaceteRetratil());

        System.out.println(b.abreAsas());
        System.out.println(b.abreAsas());
        System.out.println(b.abreAsas());
        System.out.println(b.abreAsas());
        System.out.println(b.abreAsas());
        System.out.println(b.abreAsas());

        System.out.println(b.disparaLaser());
        System.out.println(b.golpesDeKarate());

    }
}
