/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import edu.princeton.cs.algs4.Draw;

public class App {

    public static void main(String[] args) {

        // Lib para interface gráfica.
        Draw draw = new Draw();
        draw.text(.5, .5, "Gabriela");
    }
}
