/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aula;

import java.util.*;

public class App {
    public static void main(String[] args) {
//        DiaDaSemana[] aulas = {DiaDaSemana.TER, DiaDaSemana.QUI};
//
//        for(DiaDaSemana d: aulas) {
//            System.out.println(d);
//        }
//        int disco = aulas[0].codigo;
//        DiaDaSemana relatorio = DiaDaSemana.getByCodigo(disco);
//
//        if (relatorio != null) {
//            System.out.println(relatorio);
//        }
        ArrayList<Carta> baralho = new ArrayList<>();

        for (Naipe naipe: Naipe.values()) {
            for (ValorCarta valor: ValorCarta.values()) {
                baralho.add(new Carta(valor, naipe));
            }
        }

//        for (Carta c: baralho) {
//            System.out.println(c);
//        }
        System.out.println(baralho.size());

        Collections.shuffle(baralho);
        for (Carta c: baralho) {
            System.out.println(c);
        }


    }
}
