/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static void main(String[] args) {
        //Carro c = new Carro();

        //c.obterVelocidade();
        //c.aceleraCarro(20);
        //System.out.println(c.obterVelocidade());

        Pessoa gabi = new Pessoa("Gabriela", "050505502");
        Pessoa sofia = new Pessoa("Sofia", "75874864");

        Estudante e = new Estudante(17, "Leonardo", "Design");

        System.out.println(e.toString());
    }
}
