/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        int[] moedas = new int[6];

        boolean flag = true;
        while (flag) {
            System.out.println("Digite o valor da moeda em centavos ou zero para sair do programa: ");
            switch (scanner.nextLine()) {
                case "1":
                    moedas[0]++;
                    break;
                case "5":
                    moedas[1]++;
                    break;
                case "10":
                    moedas[2]++;
                    break;
                case "25":
                    moedas[3]++;
                    break;
                case "50":
                    moedas[4]++;
                    break;
                case "100":
                    moedas[5]++;
                    break;
                case "0":
                    flag = false;
                    break;
                default:
                    System.out.println("Valor invalido!");
            }
        }
        System.out.printf("\nMoedas:\nR$0,01 - %s\nR$0,05 - %s\nR$0,10 - %s\nR$0,25 - %s\nR$0,50 - %s\nR$1,00 - %s\n", moedas[0], moedas[1], moedas[2], moedas[3], moedas[4], moedas[5]);
    }
}
